name: "dev"
windows: 
    - name: main
      root: /var/www/html/php
      focus: true
      layout: tiled
      panes:
          - commands:
              - ["svn up ."]

    - name: nodejs
      root: ~
      layout: tiled
      panes:
          - commands:
              - ["node"]

    - name: python
      root: ~
      layout: tiled
      panes:
          - commands:
              - ["ipython"]
          - commands:
              - ["ipython3"]

